name: check dependency updates

on:
  schedule:
    - cron:  '0 0 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      TERM: dumb

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check dependency updates
        run: ./gradlew dependencyUpdates

      - name: Upload dependency updates report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-updates
          path: app/build/outputs/apk/debug/dependencyUpdates
